
                     ASP OMBUDSMAN STATEMENT

Jazz Jackrabbit is produced by a member of the Association of Shareware
Professionals (ASP).  ASP wants to  make  sure  that  the  shareware
principle   works   for  you.   If  you  are  unable  to  resolve  a
shareware-related problem  with  an  ASP  member  by  contacting the
member directly, ASP may be able to help.  The ASP  Ombudsman  (OMB)
can  help  you  resolve a dispute or problem with an ASP member, but
does not provide  technical  support  for members' products.  Please
write to  the  ASP  Ombudsman  at  545  Grover  Road,  Muskegon,  MI
49442-9427  or  send a CompuServe message via CompuServe Mail to ASP
Ombudsman 70007,3536.  The OMB may be contacted by FAX by sending to
the ASP FAX number: (616)  788-2765.   In communication with the OMB
please include a telephone and/or FAX number if available.

                       _______
                  ____|__     |                (R)
               --|       |    |-------------------
                 |   ____|__  |  Association of
                 |  |       |_|  Shareware
                 |__|   o   |    Professionals
               -----|   |   |---------------------
                    |___|___|    MEMBER

